apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ersatztv-config-claim
  namespace: apps
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
