apiVersion: v1
kind: PersistentVolume
metadata:
  name: ersatztv-config-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/opt/ersatztv/config"  # host path for config storage
