apiVersion: v1
kind: Service
metadata:
  name: prometheus-bridge-svc
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app: prometheus-bridge
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30080

