apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dashdot-config-claim
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "manual"
  resources:
    requests:
      storage: 1Gi
  volumeName: dashdot-config-pv

