apiVersion: v1
kind: PersistentVolume
metadata:
  name: dashdot-config-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "manual"
  hostPath:
    path: "/opt/dashdot/config"

