# Tdarr Helm values.yaml (server only)
image:
  repository: ghcr.io/haveagitgat/tdarr
  tag: 2.45.01
  pullPolicy: IfNotPresent

env:
  PUID: "1000"
  PGID: "1000"
  TZ: "Asia/Jerusalem"
  # Point nodes at the in-cluster service
  serverURL: "http://tdarr:8266"
  NODE_OPTIONS: "--dns-result-order=ipv4first"
  ffmpegPath: "/usr/local/bin/ffmpeg"
  LIBVA_DRIVER_NAME: "iHD"

ingress:
  main:
    enabled: false

service:
  main:
    ports:
      http:
        port: 8265
      server:
        enabled: true
        port: 8266

persistence:
  config:
    enabled: true
    existingClaim: tdarr-config-claim
  data:
    enabled: true
    existingClaim: tdarr-data-claim
  media:
    enabled: true
    mountPath: "/mnt"
    existingClaim: tdarr-media-claim
  shared:
    enabled: true
    emptyDir: {}

podSecurityContext:
  supplementalGroups:
    - 993   # host "render" group GID

fullnameOverride: "tdarr"

resources:
  requests:
    cpu: "250m"
    memory: "256Mi"
  limits:
    cpu: "1"
    memory: "1Gi"

# Turn OFF the bundled node sidecar
node:
  enabled: false

