apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-config-claim
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""        # Match the PV's storageClassName
  resources:
    requests:
      storage: 1Gi

