apiVersion: v1
kind: Service
metadata:
  name: bazarr-service
  namespace: apps
spec:
  type: NodePort
  selector:
    app: bazarr
  ports:
  - port: 6767
    targetPort: 6767
    nodePort: 30677
    protocol: TCP

