apiVersion: apps/v1
kind: Deployment
metadata:
  name: bazarr
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bazarr
  template:
    metadata:
      labels:
        app: bazarr
    spec:
      hostNetwork: true
      containers:
        - name: bazarr
          image: ghcr.io/linuxserver/bazarr:latest
          ports:
            - containerPort: 6767
          volumeMounts:
            - name: config-volume
              mountPath: /config
            - name: media-volume
              mountPath: /mnt
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Asia/Jerusalem"
            - name: HTTP_PROXY
              value: "http://192.168.1.148:3128"
            - name: HTTPS_PROXY
              value: "http://192.168.1.148:3128"
      volumes:
        - name: config-volume
          persistentVolumeClaim:
            claimName: bazarr-config-claim
        - name: media-volume
          hostPath:
            path: /mnt
            type: Directory

