apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bazarr-config-claim
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: bazarr-config-pv

