apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yt2radarr-config-claim
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  volumeName: yt2radarr-config-pv
  storageClassName: ""

