apiVersion: v1
kind: PersistentVolume
metadata:
  name: yt2radarr-config-pv
  namespace: apps
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /opt/yt2radarr/config

