apiVersion: v1
kind: PersistentVolume
metadata:
  name: agregarr-config-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/opt/agregarr/config"
