apiVersion: v1
kind: Service
metadata:
  name: agregarr
  namespace: apps
spec:
  selector:
    app: agregarr
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
  type: ClusterIP
