apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: agregarr-config-claim
  namespace: apps
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
